
application: global-paths
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /photos
  static_dir: photos

- url: /.*
  script: gps.application

- url: /counselor/.*
  script: gps.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest


#- url: /(.*)
#  static_files: \1
#  upload: (.*)
